### ISSUE TITLE
关于英文标题的换行问题，以及其他

### ISSUE THREAD

**Issue by zshicode** [kongxiao0532/nku_bachelor_thesis#1]
- 关于英文标题换行问题，可以把`NKThesis.cfg`中的
`英文题目：\hskip 0.5em & \parbox[t]{6cm}{\uline{\NKT@keyvalue{lunwentimuy}\hfill}}`
直接换成自己论文的英文标题，例如：
`英文题目：\hskip 0.5em & \parbox[t]{12cm}{\uline{Title of Thesis\hfill}}`
然后就能正常换行。

- 标题部分的`parbox`宽度只有6cm，可能略窄，按照学校的Word模板，宽度设为12cm应该没有问题。

- 另外，建议大家使用版本比较新的TexLive或者MacTex，因为版本太旧的biblatex没法编译参考文献那块。

**Comment by zshicode** [comment]
另外，按照学校的模板，封面个人信息的顺序应该是：学号、姓名、年级、专业、系别、学院、指导教师、完成日期。

**Comment by kongxiao0532** [comment]
* 关于英文换行问题，我测试过在NKThesis.cfg中直接写没问题，但是用变量就导致不能换行。我是不知道这个问题该怎么解决。
* 标题部分看个人喜好吧，模板中个人信息部分也长很多。
* 封面顺序我是参照计控下发的指导手册改的，章节标题也是参照计控的格式，和学校下发的确实有不同。

**Comment by zshicode** [comment]
> 
> 
>     * 关于英文换行问题，我测试过在NKThesis.cfg中直接写没问题，但是用变量就导致不能换行。我是不知道这个问题该怎么解决。
> 
>     * 标题部分看个人喜好吧，模板中个人信息部分也长很多。
> 
>     * 封面顺序我是参照计控下发的指导手册改的，章节标题也是参照计控的格式，和学校下发的确实有不同。

好的，谢谢。

**Comment by yzz951029** [comment]
你好，我遇到了font not found的问题，想问下怎么解决？
"fontspec error: "font-not-found"
The font  "[fzckjw] " cannot be found.

看了一下是方正粗楷的字体，但是这个字体我已经安装在了我的C:\Windows\Fonts文件夹下，其他的像word之类的也是可以使用这个字体的。

**Comment by dogloving** [comment]
> 你好，我遇到了font not found的问题，想问下怎么解决？
> "fontspec error: "font-not-found"
> The font "[fzckjw] " cannot be found.
> 
> 看了一下是方正粗楷的字体，但是这个字体我已经安装在了我的C:\Windows\Fonts文件夹下，其他的像word之类的也是可以使用这个字体的。

试试下载这个字体放到C:\Windows\Fonts目录下
链接：https://pan.baidu.com/s/1l-hXeztCEc7x0neZUuBPiQ 
提取码：f31b

**Comment by yzz951029** [comment]
> > 你好，我遇到了font not found的问题，想问下怎么解决？
> > "fontspec error: "font-not-found"
> > The font "[fzckjw] " cannot be found.
> > 看了一下是方正粗楷的字体，但是这个字体我已经安装在了我的C:\Windows\Fonts文件夹下，其他的像word之类的也是可以使用这个字体的。
> 
> 试试下载这个字体放到C:\Windows\Fonts目录下
> 链接：https://pan.baidu.com/s/1l-hXeztCEc7x0neZUuBPiQ
> 提取码：f31b


还是报了一样的错
j:/NKU_Bachelor_Thesis_Template/main.tex:60: fontspec error: "font-not-found"
! 
! The font "[fzckjw]" cannot be found.

**Comment by kongxiao0532** [comment]
> 你好，我遇到了font not found的问题，想问下怎么解决？
> "fontspec error: "font-not-found"
> The font "[fzckjw] " cannot be found.
> 
> 看了一下是方正粗楷的字体，但是这个字体我已经安装在了我的C:\Windows\Fonts文件夹下，其他的像word之类的也是可以使用这个字体的。

我也曾经遇到相同的问题，最后解决方法是删掉粗楷以后，从方正官网重新下载安装就可以了。

**Comment by yzz951029** [comment]
> > 你好，我遇到了font not found的问题，想问下怎么解决？
> > "fontspec error: "font-not-found"
> > The font "[fzckjw] " cannot be found.
> > 看了一下是方正粗楷的字体，但是这个字体我已经安装在了我的C:\Windows\Fonts文件夹下，其他的像word之类的也是可以使用这个字体的。
> 
> 我也曾经遇到相同的问题，最后解决方法是删掉粗楷以后，从方正官网重新下载安装就可以了。

我之前电脑里没有方正粗楷，我就是从官网下载再装进去的

**Comment by 1511426** [comment]
请问写完了怎么转word呢

**Comment by yzz951029** [comment]
> 请问写完了怎么转word呢

直接在网上找PDF转换WORD的网站吧

**Comment by dogloving** [comment]
> > 请问写完了怎么转word呢
> 
> 直接在网上找PDF转换WORD的网站吧

公式是要重新打吗

**Comment by CalvinShi** [comment]
> > > 请问写完了怎么转word呢
> > 
> > 
> > 直接在网上找PDF转换WORD的网站吧
> 
> 公式是要重新打吗

可以用pandoc把PDF转成Word，另外挺多学院本科论文可以PDF的吧。。。

**Comment by zshicode** [comment]
可以用pandoc从tex源码得到Word文档，另外挺多学院本科毕业论文接受PDF的吧。。。

**Comment by guitlison** [comment]
您好！中文标题在首页不显示，是方正字体的问题吗？

**Comment by kongxiao0532** [comment]
> 您好！中文标题在首页不显示，是方正字体的问题吗？


由于我现在手里没有编译环境，我没有进行测试，但是这个方法应该都能解决你的问题。

1. 删除方正粗楷的定义。字体的定义在NKfonts.cfg中，可以将line 14的粗楷定义删除。

2. 将使用粗楷体的地方改成普通楷体。论文的格式定义在NKThesis.cfg中，可以将89行的\cukai改为\kaiti。

**Comment by XDo0** [comment]
> > > 你好，我遇到了font not found的问题，想问下怎么解决？
> > > "fontspec error: "font-not-found"
> > > The font "[fzckjw] " cannot be found.
> > > 看了一下是方正粗楷的字体，但是这个字体我已经安装在了我的C:\Windows\Fonts文件夹下，其他的像word之类的也是可以使用这个字体的。
> > 
> > 
> > 我也曾经遇到相同的问题，最后解决方法是删掉粗楷以后，从方正官网重新下载安装就可以了。
> 
> 我之前电脑里没有方正粗楷，我就是从官网下载再装进去的

我也遇到这个问题了，虽然学长or学姐已经毕业了，给之后用到这个模板的人说一下我的解决办法：
**以管理员身份运行 字体安装文件**

**Comment by zzeitt** [comment]
> > > > 你好，我遇到了font not found的问题，想问下怎么解决？
> > > > "fontspec error: "font-not-found"
> > > > The font "[fzckjw] " cannot be found.
> > > > 看了一下是方正粗楷的字体，但是这个字体我已经安装在了我的C:\Windows\Fonts文件夹下，其他的像word之类的也是可以使用这个字体的。
> > > 
> > > 
> > > 我也曾经遇到相同的问题，最后解决方法是删掉粗楷以后，从方正官网重新下载安装就可以了。
> > 
> > 
> > 我之前电脑里没有方正粗楷，我就是从官网下载再装进去的
> 
> 我也遇到这个问题了，虽然学长or学姐已经毕业了，给之后用到这个模板的人说一下我的解决办法：
> **以管理员身份运行 字体安装文件**

解决问题，不胜感激😭
